spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost/batch?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: buser
      password: qwer1234!
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: never
